### ISSUE TITLE
can't complete orders

### ISSUE THREAD

**Issue by ooples** [fraudlabspro/magento2#5]
I have attached what I see when I try to complete orders but it seems to be an issue caused by the fraud labs pro module because after installing it, my complete option completely disappeared
![no_complete](https://cloud.githubusercontent.com/assets/3075685/20875579/74c1d3e0-ba81-11e6-80ba-4f68f1e85223.png)

**Comment by fraudlabspro-com** [comment]
Hi, the order status is depends your payment settings. Have you tried with FraudLabs Pro plugin disabled?

**Comment by ooples** [comment]
I'm talking about the fact that the completed status is missing and it
works when fraudlabs pro is disabled

**Comment by fraudlabspro-com** [comment]
May I know what payment gateway are you using?
