### ISSUE TITLE
Magestore_Webpos

### ISSUE THREAD

**Issue by NTK-2016** [fraudlabspro/magento2#7]
Issue on shipping addres
Error occurred during "shipping_address" processing. Error occurred during "id" processing. Invalid type for value: "". Expected Type: "int"."
magento 2.2.2
![image](https://user-images.githubusercontent.com/24722367/72790599-ea5ee700-3c5b-11ea-9bdc-f6532c0db354.png)

**Comment by fraudlabspro-com** [comment]
Hi @NTK-2016 

It is working fine based on our testing. Can you send an email to support@fraudlabspro.com about the detail steps to reproduce the error?
